blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='all'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('equipment/', include('equipments.urls', namespace='equipments')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path

from .import views

app_name = 'equipments'

urlpatterns = [
    path('tractors/', views.TractorListView.as_view(),
         name='tractors-list'),
    path('user-tractors/', views.UserTractorListView.as_view(),
         name='user-tractors-list'),
    path('add-tractor/', views.TractorAddView.as_view(), name='tractor-add'),
    path('tractor/<int:pk>/', views.TractorDetailView.as_view(),
         name='tractor-detail'),
    path('tractor/<int:pk>/update/', views.TractorUpdateView.as_view(),
         name='tractor-update'),
    path('tractor/<int:pk>/delete/', views.TractorDeleteView.as_view(),
         name='tractor-delete'),
    path('implements/', views.ImplementListView.as_view(),
         name='implements-list'),
    path('user-implements/', views.UserImplementListView.as_view(),
         name='user-implements-list'),
    path('add-implement/', views.ImplementAddView.as_view(),
         name='implement-add'),
    path('implement/<int:pk>/detail/', views.ImplementDetailView.as_view(),
         name='implement-detail'),
    path('implement/<int:pk>/update/', views.ImplementUpdateView.as_view(),
         name='implement-update'),
    path('implement/<int:pk>/delete/', views.ImplementDeleteView.as_view(),
         name='implement-delete'),
    path('subcategory/', views.implement_subcategory, name='subcategory'),
    path('tractor/category/<int:pk>/', views.TractorCategoryList.as_view(),
         name='tractor-category'),
    path('implement/category/<int:pk>/', views.ImplementCategoryList.as_view(),
         name='implement-category'),
]

equipments/models.py
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField

from django.contrib.auth import get_user_model

User = get_user_model()


class TractorCategory(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='tractor_category',
                              blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Tractor Categories'

    def __str__(self):
        return self.name


DRIVE_TYPE = (
    (None, 'Please Select'),
    ('two wheel drive', 'Two wheel Drive'),
    ('four wheel drive', 'Four wheel Drive'),
)
TRANSMISSION_MODE = (
    (None, 'Please Select'),
    ('gear', 'Gear'),
    ('manual', 'Manual'),
    ('hydrostatic', 'Hydrostatic'),
    ('turbochanged', 'Turbocharged'),
)
HITCHING_TYPE = (
    (None, 'Please Select'),
    ('two point hitches', 'Two-point hitches'),
    ('three point hitches', 'Three-point hitches'),
)
ATTACHMENT_MODE = (
    (None, 'Please select'),
    ('frontend loader', 'frontend loader'),
    ('backhoe', 'Backhoe'),
    ('both', 'Both'),
)
FARM_SERVICES = (
    ('soil cultivations', 'Soil cultivations'),
    ('planting', 'Planting'),
    ('haversting/post-haversting', 'Haversting/Post-Haversting'),
    ('fertilizing & pest-control', 'Fertilizing & Pest-control'),
    ('drainage & irrigation', 'Drainage & Irrigation'),
    ('loading', 'Loading'),
    ('hay making', 'Hay making'),
    ('miscellaneous', 'Miscellaneous'),
)


class Tractor(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tractor_type = models.ForeignKey(
        TractorCategory, verbose_name='What type of Tractor?',
        on_delete=models.SET('others'))
    drive_type = models.CharField(
        max_length=100, verbose_name='What Drive Type', choices=DRIVE_TYPE)
    name = models.CharField(
        max_length=200, verbose_name='Name/Models of Tractor',
        help_text='eg. John Deere 6190R')
    mode_of_transmission = models.CharField(
        max_length=100, verbose_name='Mode of Transmission',
        choices=TRANSMISSION_MODE)
    engine_hp = models.PositiveIntegerField(
        verbose_name='Engine Horse Power (eg. 75hp)')
    drawbar_hp = models.PositiveIntegerField(
        verbose_name='Drawbar Horse Power (eg. 65hp)')
    pto_hp = models.PositiveIntegerField(
        verbose_name='PTO Horse Power (eg. 85hp)')
    hydraulic_capacity = models.CharField(
        max_length=100, help_text='Use a SI units of gpm or psi',
        verbose_name=('Hydaulic capacity (gallon per minutes(gpm)'
                      ' or psi-pound per square inchies)'))
    type_of_hitching = models.CharField(
        max_length=100, verbose_name='What is Hitching type?',
        choices=HITCHING_TYPE)
    cab = models.BooleanField(verbose_name='Does have a cab?', default=False)
    rollover_protection = models.BooleanField(
        verbose_name='Does have the rollover protection?', default=False)
    fuel_consumption = models.PositiveIntegerField(
        verbose_name='Fuel consumption (gallon per hour on operation)')
    attachment_mode = models.CharField(
        max_length=100, verbose_name='What mode of attachment?',
        choices=ATTACHMENT_MODE)
    operator = models.BooleanField(default=False,
                                   verbose_name='Do you have an operator(s)?')
    file = models.FileField(
        upload_to='tractors_photos/',
        verbose_name='Upload the Tractor pictures',
        help_text=('Upload quality picture of real tractor you have,'
                   ' only 5 picture.'))
    other_informations = models.TextField(
        blank=True, verbose_name='Describe your Tractor')
    price_hour = models.PositiveIntegerField(
        verbose_name='Specify the price per Hour in TShs.')
    price_hectare = models.PositiveIntegerField(
        verbose_name='Specify the price per Hectare')
    farm_services = MultiSelectField(
        choices=FARM_SERVICES,
        verbose_name='What are farming service(s) do you offer?')
    agree_terms = models.BooleanField(
        default=False, verbose_name='Do your Accept our Terms and Conditions?')
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('equipments:tractor-detail', kwargs={'pk': self.id})


class ImplementCategory(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='implements_category',
                              blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Implement Categories'

    def __str__(self):
        return self.name


class ImplementSubCategory(models.Model):
    category = models.ForeignKey(ImplementCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Implement Subcategories'

    def __str__(self):
        return self.name


OPERATION_MODE = (
    (None, 'Please Select'),
    ('tractor drive', 'Tractor drive'),
    ('self-propelled', 'Self-propelled'),
)


class Implement(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=100, verbose_name='Name/Models of Implement')
    category = models.ForeignKey(
        ImplementCategory, on_delete=models.SET('others'),
        verbose_name='What category of your Implement')
    subcategory = models.ForeignKey(
        ImplementSubCategory, on_delete=models.SET('others'),
        verbose_name='What is subcategory of your Implement')
    width = models.PositiveIntegerField(
        verbose_name='Width of the Implement', help_text='SI UNITS in metre',)
    weight = models.PositiveIntegerField(
        verbose_name='Weight of the Implement', help_text='SI UNITS in KG')
    operation_mode = models.CharField(
        max_length=100, choices=OPERATION_MODE,
        verbose_name='What is mode of operation?')
    pto = models.PositiveIntegerField(
        verbose_name='What is Horse Power required for Operation?')
    hydraulic_capacity = models.CharField(
        max_length=100,
        verbose_name='What is Hydaulic capacity required to lift?')
    operator = models.BooleanField(verbose_name='Do you have an operator(s)?')
    file = models.FileField(
        upload_to='implements_photos/',
        verbose_name='Upload the Implement pictures',
        help_text=("Upload quality picture of real implement you have,"
                   " only 5 pictures."))
    other_informations = models.TextField(
        blank=True, verbose_name='Describe your Implement')
    price_hour = models.PositiveIntegerField(
        verbose_name='Specify the price per Hour')
    price_hectare = models.PositiveIntegerField(
        verbose_name='Specify the price per Hectare')
    agree_terms = models.BooleanField(
        default=False, verbose_name='Do your Accept our Terms and Conditions?')
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('equipments:implement-detail', kwargs={'pk': self.id})

equipments/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import (
    ListView, TemplateView, DetailView, CreateView, DeleteView, UpdateView,
    FormView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


from .forms import TractorForm, ImplementForm
from .models import (Tractor, Implement, ImplementSubCategory,
                     TractorCategory, ImplementCategory)


class TractorView(LoginRequiredMixin, FormView):
    form_class = TractorForm
    template_name = 'equipments/tractor_form.html'
    success_url = reverse_lazy('equipments:tractors')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file')
        if request.method == 'POST':
            if form.is_valid():
                form.instance.user = self.request.user
                for file in files:
                    # to do
                    pass
                form.save()
                return self.form_valid(form)
            else:
                return self.form_invalid(form)


class ImplementView(LoginRequiredMixin, CreateView):
    form_class = ImplementForm
    template_name = 'equipments/implement_form.html'
    success_url = reverse_lazy('equipments:implements')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file')
        if request.method == 'POST':
            if form.is_valid():
                form.instance.user = self.request.user
                for file in files:
                    # to do
                    pass
                form.save()
                return self.form_valid(form)
            else:
                context = {
                    'form': form,
                }
                return render(request, 'equipments/implement_form.html', context)

              
class TractorListView(ListView):
    """A view for showing all the approved tractors.

    The owner must accept terms and conditions for it to be shown here.
    """
    queryset = Tractor.objects.filter(agree_terms=True, approved=True)



class ListTractor(LoginRequiredMixin, ListView):
    model = Tractor
    template_name = 'equipments/tractors.html'
    context_object_name = 'tractors'

class UserTractorListView(LoginRequiredMixin, ListView):
    """A view for showing tractors added by a particular user.


    - User must be logged in.
    """
    template_name = 'equipments/user_tractor_list.html'


    def get_queryset(self):
        return Tractor.objects.filter(user=self.request.user)



class TractorDetailView(DetailView):
    """A view for showing all details for a single tractor."""
    model = Tractor


class TractorAddView(LoginRequiredMixin, CreateView):
    """A view for adding a Tractor.

    - User must be logged in.
    """
    form_class = TractorForm
    template_name = 'equipments/tractor_form.html'
    success_url = reverse_lazy('equipments:user-tractors-list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



class ListImplement(LoginRequiredMixin, ListView):
    model = Implement
    template_name = 'equipments/implements.html'
    context_object_name = 'implements'

class TractorUpdateView(LoginRequiredMixin, UpdateView):
    """A view for updating a tractor.


    - User must be logged in.
    - User can update the tractor he/she added only.
    """
    form_class = TractorForm
    template_name = 'equipments/update_tractor_form.html'
    success_url = reverse_lazy('equipments:user-tractors-list')




class UpdateTractor(LoginRequiredMixin, UpdateView):
    form_class = TractorForm
    template_name = 'equipments/update_tractor_form.html'
    success_url = reverse_lazy('equipments:tractors')
    queryset = Tractor.objects.all()

    def get_queryset(self):
        return Tractor.objects.filter(user=self.request.user)


class TractorDeleteView(LoginRequiredMixin, DeleteView):
    """A view to confirm deletion of the Tractor.

    - User must be logged in.
    - User can delete the tractor he/she added only.
    """
    success_url = reverse_lazy('equipments:user-tractors-list')

    def get_queryset(self):
        return Tractor.objects.filter(user=self.request.user)

      
class UpdateImplement(LoginRequiredMixin, UpdateView):
    form_class = ImplementForm
    template_name = 'equipments/update_implement_form.html'
    success_url = reverse_lazy('equipments:implements')
    queryset = Implement.objects.all()


class DeleteTractor(LoginRequiredMixin, DeleteView):
    model = Tractor
    success_url = reverse_lazy('equipments:tractors')


class DeleteImplement(LoginRequiredMixin, DeleteView):

class ImplementListView(ListView):
    """A view showing list of approved implements.

    The owner must accept terms and conditions for it to be shown.
    """
    queryset = Implement.objects.filter(agree_terms=True, approved=True)


class UserImplementListView(LoginRequiredMixin, ListView):
    """A view for showing implements added by a particular user.

    - User must be logged in.
    """
    template_name = 'equipments/user_implement_list.html'

    def get_queryset(self):
        return Implement.objects.filter(user=self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ImplementDetailView(DetailView):
    """A view for showing details of single implement."""
    model = Implement

class ImplementAddView(LoginRequiredMixin, CreateView):
    """A view for adding an Implement.
    
    - User must be logged in.
    """
    form_class = ImplementForm
    template_name = 'equipments/implement_form.html'
    success_url = reverse_lazy('equipments:user-implements-list')


class ImplementUpdateView(LoginRequiredMixin, UpdateView):
    """A view to update the implement.

    - User must be logged in.
    - User can update the tractor he/she added only.
    """
    form_class = ImplementForm
    template_name = 'equipments/update_implement_form.html'
    success_url = reverse_lazy('equipments:user-implements-list')

    def get_queryset(self):
        return Implement.objects.filter(user=self.request.user)


class ImplementDeleteView(LoginRequiredMixin, DeleteView):
    """A view to confirm deletion of the Implement.

    - User must be logged in.
    - User can delete the implement he/she added only.
    """
    success_url = reverse_lazy('equipments:user-implements-list')

    def get_queryset(self):
        return Implement.objects.filter(user=self.request.user)


class TractorCategoryList(ListView):
    model = Tractor
    template_name = 'equipments/tractor_category_list.html'

    def get_queryset(self):
        self.tractor_type = get_object_or_404(TractorCategory, pk=self.kwargs['pk'])
        return Tractor.objects.filter(tractor_type=self.tractor_type)

    def get_context_data(self, **kwargs):
        context = super(TractorCategoryList, self).get_context_data(**kwargs)
        context['category'] = self.tractor_type
        return context


class ImplementCategoryList(ListView):
    template_name = 'equipments/implement_category_list.html'

    def get_queryset(self):
        self.category = get_object_or_404(
            ImplementCategory, pk=self.kwargs['pk'])
        return Implement.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


def implement_subcategory(request):
    category_id = request.GET.get('category')
    subcategories = ImplementSubCategory.objects.filter(
        category_id=category_id).order_by('name')
    return render(request, 'equipments/subcategory.html', {'subcategories': subcategories})

equipments/templates/equipments/implement_category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<!-- Inner Page Breadcrumb -->
	<section class="inner_page_breadcrumb bgc-orange" aria-label="breadcrumb">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h4 class="breadcrumb_title float-left">{{category.name}} Implements</h4>
					<ol class="breadcrumb float-right">
					    <li class="breadcrumb-item"><a href="/">Home</a></li>
					    <li class="breadcrumb-item active" aria-current="page">{{category.name}}</li>
					</ol>
				</div>
			</div>
		</div>
	</section>



	<section class="bgc-fa">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-xl-3 dn-smd">
					<div class="faq_search_widget mb30">
						<h4 class="fz20 mb15">Location</h4>
						<div class="input-group mb-3">
							<input type="text" class="form-control" placeholder="All Location" aria-label="Recipient's username" aria-describedby="button-addon2">
							<div class="input-group-append">
						    	<button class="btn btn-outline-secondary" type="button" id="button-addon3"><span class="flaticon-location-pin"></span></button>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12 col-lg-9 col-xl-9">
					<div class="row">
                        {% for implement in object_list %}
						<div class="col-lg-12">
							<div class="fj_post style2">
								<div class="details">
									<h5 class="job_chedule text-orange">{{implement.category.name}}</h5>
									<div class="thumb">
										<img class="img-fluid" src="{{implement.category.image.url}}" alt="image" style="width: 100px; height: auto;">
									</div>
                                    <a href=""><h4>{{implement.name}}</h4></a>
                                    <a class="view-more" href="">view more</a>
                                    <br>
                                    <hr>
									<ul class="featurej_post">
										<li class="list-inline-item"><span class="flaticon-location-pin"></span>Bothell, WA, USA</li>
										<li class="list-inline-item"><span class="flaticon-price pl20"></span>Tshs. {{implement.price_hour}}/= per hour</li>
                                    </ul>
								</div>
								<a class="btn btn-cart" href="#">Add to Cart</a>
							</div>
                        </div>
                        {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

equipments/templates/equipments/implement_confirm_delete.html
{% extends 'dashboard-base.html' %}
{% load crispy_forms_tags %}

{% block content %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container">
        <div class="card">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="alert alert-warning" role="alert">Do you want to delete <strong>{{implement.name}} - Implement</strong>?</div>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock content %}

equipments/templates/equipments/implement_detail.html
{% extends 'base.html' %}
{% load static %}



{% block stylesheet %}

{% endblock stylesheet %}


{% block content %}
	<!-- Inner Page Breadcrumb -->
	<section class="inner_page_breadcrumb bgc-orange" aria-label="breadcrumb">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h4 class="breadcrumb_title float-left">All Equipments</h4>
					<ol class="breadcrumb float-right">
					    <li class="breadcrumb-item"><a href="#">Home</a></li>
					    <li class="breadcrumb-item active" aria-current="page">All Equipments</li>
					</ol>
				</div>
			</div>
		</div>
    </section>

    <!--Tractor one page -->
    <section class="single-equipment-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-xl-3">
                    <img src="{% static 'main/images/compact.png' %}" alt="">
                </div>
                <div class="col-lg-6 col-xl-6">
                    <div class="candidate_personal_info style2">
						<div class="details">
							<span class="text-orange fwb">Full Time</span>
							<h4>UX/UI Designer Web & Mobile Platforms</h4>
							<p>
                                Due to ongoing growth, this fun & energetic International corporate based on the outskirts of Oxford, is seeking a UX/UI Designer to join an innovative team, focused on delivering exciting User Experiences and great functionality, across both Web & Mobile platforms.
                            </p><br>
                            <hr>
                            <p><strong>Pricing and Location</strong></p>
							<ul class="address_list">
								<li class="list-inline-item"><span class="flaticon-location-pin"></span> Bothell, WA, USA</li>
								<li class="list-inline-item"><span class="flaticon-price"></span> $13.00 - $18.00 per hour</li>
							</ul>
						</div>
					</div>
                </div>
                <div class="col-lg-3 col-xl-3">
                    <div class="candidate_personal_overview style3">
                        <p class="small_txt">Sign in to view account pricing</p>
                        <div class="text-center">
                            <label for="">Start Date</label>
                        <input id="datepicker">
                        <label for="">End Date</label>
                        <input id="datepicker">
                        <label for="">Quantity</label>
                        <input type="text">
                        <label for="">Transport</label>
                        <input type="text">
                        </div>

                        <br><br>
                        <a class="btn btn-block btn-primary" href="">Add to cart</a>


					</div>
                </div>
            </div>
        </div>

    </section>


    <section class="expert-freelancer bgc-fa pb20">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="ulockd-main-title">
						<h4>SIMILAR EQUIPMENTS</h4>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="ef_slider2">
						{% for implement in implements %}
						<div class="item">
							<div class="ef_post home6">
								<div class="ef_header">
                                    <h4 class="hr_rate">{{tractor.tractor_type.name}}</h4>
                                    <h5>{{tractor.name}}</h5>
								</div>
								<a href="{% url 'equipments:implement-detail' implement.id %}">
									<div class="thumb text-center" style="margin-top: 100px;">
										<img class="img-fluid" src="{{implement.file.url }}" alt="">
									</div>
								</a>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>



    {% block javascript %}

    {% endblock javascript %}



{% endblock %}

equipments/templates/equipments/implement_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <section class="section-two bg-light">
    <div class="mt-100 custom-form">
      <form id="implementForm" data-subcategories-url="{% url 'equipments:subcategory' %}" method="POST" class="col-md-8 offset-md-2 card" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div class="card-body">
          <div class="text-center">
            <h4 class="mb-4 pb-2 pt-2">Add your implement</h4>  
          </div>
          <div class="form-group">
            {{ form | crispy }}
            <button type="submit" class="btn btn-green mt-2">Add implement</button>
          </div>
        </div>
      </form>
    </div>
  </section>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <script>
    $("#id_category").change(function () {
      var url = $("#implementForm").attr("data-subcategories-url");
      var categoryId = $(this).val();  
      $.ajax({                       
        url: url,
        data: {
          'category': categoryId
        },
        success: function (data) { 
          $("#id_subcategory").html(data); 
        }
      });

    });
  </script>

{% endblock content %}

equipments/templates/equipments/subcategory.html
<option value="">---------</option>
{% for subcategory in subcategories %}
<option value="{{ subcategory.pk }}">{{ subcategory.name }}</option>
{% endfor %}

equipments/templates/equipments/tractor_category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<!-- Inner Page Breadcrumb -->
	<section class="inner_page_breadcrumb bgc-orange" aria-label="breadcrumb">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h4 class="breadcrumb_title float-left">{{category.name}}s</h4>
					<ol class="breadcrumb float-right">
					    <li class="breadcrumb-item"><a href="/">Home</a></li>
					    <li class="breadcrumb-item active" aria-current="page">{{category.name}}</li>
					</ol>
				</div>
			</div>
		</div>
	</section>


	<!-- Our Candidate List -->
	<section class="bgc-fa">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-xl-3 dn-smd">
					<div class="faq_search_widget mb30">
						<h4 class="fz20 mb15">Location</h4>
						<div class="input-group mb-3">
							<input type="text" class="form-control" placeholder="All Location" aria-label="Recipient's username" aria-describedby="button-addon2">
							<div class="input-group-append">
						    	<button class="btn btn-outline-secondary" type="button" id="button-addon3"><span class="flaticon-location-pin"></span></button>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12 col-lg-9 col-xl-9">
					<div class="row">
                        {% for tractor in tractor_list %}
						<div class="col-lg-12">
							<div class="fj_post style2">
								<div class="details">
									<h5 class="job_chedule text-orange">{{tractor.tractor_type.name}}</h5>
									<div class="thumb">
										<img class="img-fluid" src="{{tractor.tractor_type.image.url}}" alt="image" style="width: 100px; height: auto;">
									</div>
                                    <a href=""><h4>{{tractor.name}}</h4></a>
                                    <a class="view-more" href="{% url 'equipments:tractor-detail' tractor.id %}">view more</a>
                                    <br>
                                    <hr>
									<ul class="featurej_post">
										<li class="list-inline-item"><span class="flaticon-location-pin"></span>Bothell, WA, USA</li>
										<li class="list-inline-item"><span class="flaticon-price pl20"></span>Tshs. {{tractor.price_hour}}/= per hour</li>
                                    </ul>
								</div>
								<a class="btn btn-cart" href="#">Add to Cart</a>
							</div>
                        </div>
                        {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

equipments/templates/equipments/tractor_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <section class="section-two bg-light">
    <div class="custom-form rounded shadow">
      <form method="POST" class="mt-100 col-md-8 offset-md-2 card" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
          <div class="text-center">
            <h4 class="mb-4 pb-2 pt-2">Add your Tractor</h4>  
          </div>
          <div class="form-group">
            {{form|crispy}}
          </div>
        <div>
          <button type="submit" class="btn btn-green mt-2">Submit</button>
        </div>
      </form>
    </div>
  </section>

{% endblock content %}