accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('confirm-email/<str:user_id>/<str:token>/',
         views.ConfirmRegistrationView.as_view(), name='confirm-email'),
    path('<slug:slug>/profile/', views.UserProfileView.as_view(),
         name='user-profile'),
    path('<slug:slug>/profile/update/', views.UserProfileUpdateView.as_view(),
         name='user-profile'),
    path('', include('django.contrib.auth.urls')),
]

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='all'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('equipment/', include('equipments.urls', namespace='equipments')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.Homepage.as_view(), name='name'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactUsView.as_view(), name='contact'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Fagrimacs - Make Money with Farm Equipments rental Platform</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A web platform where farmers can easy rent-out their Tractors & Implements which they don’t need and rent-in what they want to use from nearby farmers" />
        <meta name="keywords" content="fagrimacs, tractor, implement, disc plough, disc harrow, cultivator, chisel plow, power tiller, rotary tiller, rotavator, rototiller, subsoiler, Broadcast seeder" />
        <meta content="Fagrimacs" name="author" />
        <!-- favicon -->
        <link rel="shortcut icon" href="{% static 'main/images/favicon.ico' %}">
        <!-- Bootstrap css -->
        <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Icons -->
        <link href="{% static 'main/css/materialdesignicons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Icons -->
        <link href="{% static 'main/css/magnific-popup.css' %}" rel="stylesheet" type="text/css" />
        <!-- Slider -->               
        <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}"/> 
        <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}"/> 
        <!-- Main css File -->
		<link href="{% static 'main/css/style.css' %}" rel="stylesheet" type="text/css" />
		{% block stylesheet %}
		{% endblock stylesheet %}
    </head>

    <body>
        <!-- Loader Start -->
        <div id="preloader">
            <div id="status">
                <div class="sk-chase mt-4">
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                </div>
            </div>
        </div>
		<!-- Loader End -->
		

		<!-- Main Header Nav -->
		{% include 'header.html' %}

		{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-5" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				<span class="sr-only">Close</span>
			</button>
			{{ message }}
		</div>
		{% endfor %}
		{% endif %}


		{% block content %}
		{% endblock content %}


		{% include 'footer.html' %}
		
		{% include 'scripts.html' %}
    </body>
</html>

templates/dashboard-base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}Title{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {% block stylesheet %}
  {% endblock stylesheet %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'main:contact' %}" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" href="/">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">20</span>
        </a>
      </li>

      <li class="nav-item">
        {% if request.user.role == 'farmer' %}
        <a class="nav-link" href="{{ user.farmerprofile.get_absolute_url }}"> <i class="fas fa-user"></i> Profile</a>
        {% elif request.user.role == 'owner' %}
        <a class="nav-link" href="{{ user.ownerprofile.get_absolute_url }}"> <i class="fas fa-user"></i> Profile</a>
        {% elif request.user.role == 'expert' %}
        <a class="nav-link" href="{{ user.expertprofile.get_absolute_url }}"> <i class="fas fa-user"></i> Profile</a>
        {% else %}
        <a class="nav-link" href="{{ user.adminprofile.get_absolute_url }}"> <i class="fas fa-user"></i> Profile</a>
        {% endif %}
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">
          <i class="fas fa-sign-out-alt"></i>
          Logout
        </a>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->
  {% block content %}
  {% endblock content %}

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="/">Fagrimacs Enterprise</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->


{% block javascript %}
{% endblock javascript%}
<!-- jQuery -->
<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- <script src="{% static 'dashboard/js/equipment.js' %}"></script> -->
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'dashboard/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'dashboard/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'dashboard/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dashboard/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'dashboard/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'dashboard/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'dashboard/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/js/adminlte.js' %}"></script>
</body>
</html>

templates/footer.html
        <!-- Footer Start -->
        <footer class="bg-green py-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-6 col-md-4 col-md-3 col-lg-2">
                        <div class="quick_link_widget">
                            <h4>Company</h4>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'main:about' %}">About Us</a></li>
                                <li><a href="{% url 'main:contact' %}">Contact us</a></li>
                                <!-- <li><a href="#">Careers</a></li> -->
                                <li><a href="{% url 'accounts:signup' %}">Partnership</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-md-3 col-lg-3">
                        <div class="quick_link_widget">
                            <h4>Farm Equipments</h4>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'accounts:signup' %}">Rent-out Equipments</a></li>
                                <li><a href="">Place an order</a></li>
                                <!-- <li><a href="#">FAQ</a></li> -->
                                <!-- <li><a href="#">Partnership</a></li> -->
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-4 col-md-3 col-lg-3">
                        <div class="quick_link_widget">
                            <!-- <h4>Company</h4>
                            <ul class="list-unstyled">
                                <li><a href="">About company</a></li>
                                <li><a href="">Contact us</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Partnership</a></li>
                            </ul> -->
                        </div>
                    </div>
                    <div class="col-sm-8 col-md-6 col-md-3 col-lg-4">
                        <div class="newsletter_widget"> 
                            <h4>Newsletter</h4>
                            <p>Subscribe to Fagrimacs newsletter to get the latest Tractors and Implement posted, experts, and other
                                latest news - stay updated.</p>
                            <form class="form-inline mailchimp_form">
                                <label class="sr-only" for="inlineFormInputMail2">Name</label>
                                <input type="email" class="form-control mb-2 mr-sm-2" id="inlineFormInputMail2"
                                    placeholder="Enter your email address">
                                <button type="submit" class="btn btn-orange mb-2"><span class="fa fa-paper-plane-o"></span></button>
                            </form>
                        </div>
                        <ul class="list-unstyled social-icon social mb-0 mt-4">
                            <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
                            <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="instagram" class="fea icon-sm fea-social"></i></a></li>
                            <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
                            <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="linkedin" class="fea icon-sm fea-social"></i></a></li>
                        </ul><!--end icon-->
                    </div>
                </div>
            </div>
          
    <!-- Footer Start -->
	<footer class="bg-green py-5">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-sm-6 col-md-4 col-md-3 col-lg-2">
					<div class="quick_link_widget">
						<h4>Company</h4>
						<ul class="list-unstyled">
							<li><a href="">About company</a></li>
							<li><a href="">Contact us</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Partnership</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-6 col-md-4 col-md-3 col-lg-3">
					<div class="quick_link_widget">
						<h4>Company</h4>
						<ul class="list-unstyled">
							<li><a href="">About company</a></li>
							<li><a href="">Contact us</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Partnership</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-4 col-md-4 col-md-3 col-lg-3">
					<div class="quick_link_widget">
						<h4>Company</h4>
						<ul class="list-unstyled">
							<li><a href="">About company</a></li>
							<li><a href="">Contact us</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Partnership</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-8 col-md-6 col-md-3 col-lg-4">
					<div class="newsletter_widget"> 
						<h4>Newsletter</h4>
						<p>Subscribe to Fagrimacs newsletter to get the latest Tractors and Implement posted, experts, and other
							latest news - stay updated.</p>
						<form class="form-inline mailchimp_form">
							<label class="sr-only" for="inlineFormInputMail2">Name</label>
							<input type="email" class="form-control mb-2 mr-sm-2" id="inlineFormInputMail2"
								placeholder="Enter your email address">
							<button type="submit" class="btn btn-orange mb-2"><span class="fa fa-paper-plane-o"></span></button>
						</form>
					</div>
					<ul class="list-unstyled social-icon social mb-0 mt-4">
						<li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="instagram" class="fea icon-sm fea-social"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="linkedin" class="fea icon-sm fea-social"></i></a></li>
					</ul><!--end icon-->
				</div>
			</div>
		</div>

		<!-- Back to top -->    
		<a href="#" class="back-to-top" id="back-to-top" title="Top"> 
			<i class="mdi mdi-arrow-up icons bg-light text-dark"> </i> 
		</a>
		<!-- Back to top -->
	</footer><!--end footer-->
	<footer class="footer-bar bg-green">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-12 text-center">
					<p class="mb-0 footer-text para-desc mx-auto">© 2020 All Right Reserved | <a href="http://fagrimacs.com" target="_blank" class="text-reset">Fagrimacs Entreprise</a>.</p>
				</div><!--end col-->
			</div><!--end row-->
		</div><!--end container-->
	</footer><!--end footer-->
	<!-- Footer End -->

templates/header.html
{% load static %}

<!-- Navbar STart -->
<header id="topnav" class="defaultscroll sticky bg-white">
    <div class="container">
        <!-- Logo container-->
        <div>
            <a class="logo" href="/">
                <img src="{% static 'main/images/logo.png' %}" height="60" alt="logo">
            </a>
        </div>
        {% if not request.user.is_authenticated %}            
        <div class="buy-button">
            <a href="{% url 'accounts:signup' %}" class="btn btn-green">Signup</a>
        </div>
        {% endif %}
        <!-- End Logo container-->
        <div class="menu-extras">
            <div class="menu-item">
                <!-- Mobile menu toggle-->
                <a class="navbar-toggle">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </div>
        </div>

        <div id="navigation">
            <!-- Navigation Menu-->   
            <ul class="navigation-menu">
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'main:about' %}">About Us</a></li>
                <!-- <li><a href="{# url 'main:make-order' #}">Make an order</a></li> -->
                <!-- <li><a href="{% url 'blog:all' %}">Blog</a></li> -->
                <!-- <li><a href="{# url 'main:experts' #}">Hire expert</a></li> -->
                <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
                {% if request.user.is_authenticated %}
                <li class="has-submenu">
                    <a href="javascript:void(0)">My Account</a><span class="menu-arrow"></span>
                    <ul class="submenu">
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
				{% endif %}
            </ul><!--end navigation menu-->
        </div><!--end navigation-->
    </div><!--end container-->
</header><!--end header-->
<!-- Navbar End -->

templates/scripts.html
{% load  static %}

 <!-- javascript -->
 <script src="{% static 'main/js/jquery-3.5.1.min.js' %}"></script>
 <script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'main/js/jquery.easing.min.js' %}"></script>
 <script src="{% static 'main/js/scrollspy.min.js' %}"></script>
 <!-- Magnific popup -->
 <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
 <script src="{% static 'main/js/magnific.init.js' %}"></script>
 <!-- Icon -->
 <script src="{% static 'main/js/feather.min.js' %}"></script>
 <script src="https://unicons.iconscout.com/release/v2.1.9/script/monochrome/bundle.js"/></script>
 <!-- SLIDER -->
 <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
 <script src="{% static 'main/js/owl.init.js' %}"></script>
 <!-- Contact -->
 <script src="{% static 'main/js/contact.js' %}"></script>
 <!-- Main Js -->
 <script src="{% static 'main/js/app.js' %}"></script>

 
{% block javascript %}
{% endblock javascript%}